// Self-contained HTML preview for visual recap documents. No build step, no
// external CDN dependencies. Mermaid is rendered as a <pre> with a note that
// it's available if the user loads mermaid.js themselves.
import type { RecapDocument } from "../schemas.ts";

export function renderHtml(doc: RecapDocument): string {
	const json = JSON.stringify(doc, null, 2)
		.replace(/</g, "\\u003c")
		.replace(/>/g, "\\u003e")
		.replace(/&/g, "\\u0026");
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escape(doc.title)} — Visual Recap</title>
<style>
  :root {
    --bg: #0b1020;
    --fg: #e7eaf0;
    --muted: #8b93a7;
    --accent: #7aa2f7;
    --danger: #f7768e;
    --ok: #9ece6a;
    --warn: #e0af68;
    --panel: #131a2b;
    --line: #1e2640;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #fbfbfd; --fg: #1a1d24; --muted: #5b6275;
      --accent: #2a59c4; --danger: #b3261e; --ok: #1b873f; --warn: #b25b00;
      --panel: #ffffff; --line: #e5e8ef;
    }
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: var(--bg); color: var(--fg); font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; line-height: 1.5; }
  main { max-width: 980px; margin: 0 auto; padding: 32px 24px 96px; }
  h1 { font-size: 2rem; margin: 0 0 4px; }
  h2 { font-size: 1.25rem; margin: 32px 0 12px; border-bottom: 1px solid var(--line); padding-bottom: 6px; }
  h3 { font-size: 1rem; margin: 24px 0 8px; }
  .brief { color: var(--muted); font-size: 1rem; margin: 0 0 16px; }
  .meta { color: var(--muted); font-size: 0.85rem; margin: 0 0 24px; }
  .panel { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 16px 18px; margin: 12px 0; }
  .badge { display: inline-block; padding: 1px 8px; border-radius: 999px; font-size: 0.75rem; font-weight: 600; }
  .badge-A { background: rgba(158,206,106,0.18); color: var(--ok); }
  .badge-M { background: rgba(224,175,104,0.18); color: var(--warn); }
  .badge-D { background: rgba(247,118,142,0.18); color: var(--danger); }
  .badge-R { background: rgba(122,162,247,0.18); color: var(--accent); }
  .badge-C { background: rgba(187,154,247,0.18); color: #bb9af7; }
  .badge-touched, .badge-read { background: rgba(139,147,167,0.18); color: var(--muted); }
  table { border-collapse: collapse; width: 100%; margin: 8px 0; }
  th, td { padding: 6px 10px; text-align: left; border-bottom: 1px solid var(--line); font-size: 0.9rem; }
  th { color: var(--muted); font-weight: 600; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 0.85em; }
  pre { background: var(--panel); border: 1px solid var(--line); border-radius: 6px; padding: 12px 14px; overflow: auto; font-size: 0.85rem; }
  .risk { margin: 6px 0; padding: 8px 12px; border-left: 3px solid var(--accent); background: var(--panel); }
  .risk-high { border-left-color: var(--danger); }
  .risk-medium { border-left-color: var(--warn); }
  .risk-low { border-left-color: var(--ok); }
  .risk-info { border-left-color: var(--muted); }
  details summary { cursor: pointer; color: var(--accent); font-weight: 600; margin: 8px 0; }
  .timeline-item { display: flex; gap: 10px; padding: 6px 0; border-bottom: 1px dashed var(--line); }
  .timeline-item .role { flex: 0 0 100px; color: var(--muted); font-size: 0.8rem; padding-top: 2px; }
  .timeline-item .body { flex: 1; }
  .footer-note { color: var(--muted); font-size: 0.75rem; margin-top: 32px; }
</style>
</head>
<body>
<main>
  <h1 id="title"></h1>
  <p class="brief" id="brief"></p>
  <p class="meta" id="meta"></p>
  <div id="content"></div>
  <p class="footer-note">Self-contained preview generated by <code>pi-visual-recap</code>. Open the source <code>recap.md</code> for the canonical Markdown.</p>
</main>
<script id="recap-data" type="application/json">${json}</script>
<script>
(() => {
  const doc = JSON.parse(document.getElementById('recap-data').textContent);
  document.getElementById('title').textContent = doc.title;
  document.getElementById('brief').textContent = doc.brief;
  const meta = ['Target: ' + doc.target, 'Generated: ' + doc.generatedAt];
  if (doc.model) meta.push('Model: ' + doc.model.provider + '/' + doc.model.id);
  meta.push('Source: ' + doc.source);
  document.getElementById('meta').textContent = meta.join('  •  ');

  const root = document.getElementById('content');
  for (const section of doc.sections) {
    if (section.type === 'outcome') {
      const wrap = document.createElement('section');
      wrap.innerHTML = '<h2>Summary</h2><div class="panel">' + mdToHtml(section.markdown) + '</div>';
      root.appendChild(wrap);
    } else if (section.type === 'diagram') {
      const wrap = document.createElement('section');
      const inner = '<h2>' + escapeHtml(section.title) + '</h2>' +
        (section.summary ? '<p>' + escapeHtml(section.summary) + '</p>' : '') +
        '<pre>' + escapeHtml(section.mermaid) + '</pre>' +
        '<p class="footer-note">Mermaid source — load mermaid.js to render as a diagram.</p>';
      wrap.innerHTML = inner;
      root.appendChild(wrap);
    } else if (section.type === 'file-tree') {
      const wrap = document.createElement('section');
      const rows = section.entries.map((e) => {
        const badge = badgeFor(e.status);
        const delta = '+' + e.additions + '/-' + e.deletions;
        return '<tr><td><span class="badge ' + badge.cls + '">' + badge.label + '</span></td>' +
          '<td><code>' + escapeHtml(e.path) + '</code></td>' +
          '<td>' + delta + '</td>' +
          '<td>' + (e.note ? escapeHtml(e.note) : '') + '</td></tr>';
      }).join('');
      wrap.innerHTML = '<h2>' + escapeHtml(section.title || 'Changed files') + '</h2>' +
        '<table><thead><tr><th>Status</th><th>File</th><th>+/-</th><th>Note</th></tr></thead>' +
        '<tbody>' + (rows || '<tr><td colspan="4">No entries</td></tr>') + '</tbody></table>';
      root.appendChild(wrap);
    } else if (section.type === 'session-timeline') {
      const wrap = document.createElement('section');
      const items = section.items.map((it) =>
        '<div class="timeline-item"><div class="role">' + escapeHtml(it.role) + '</div>' +
        '<div class="body"><strong>' + escapeHtml(it.title) + '</strong>' +
        (it.detail ? '<div>' + escapeHtml(it.detail) + '</div>' : '') + '</div></div>'
      ).join('');
      wrap.innerHTML = '<h2>Timeline</h2><div class="panel">' + items + '</div>';
      root.appendChild(wrap);
    } else if (section.type === 'review-notes') {
      if (!section.risks.length) continue;
      const wrap = document.createElement('section');
      const items = section.risks.map((r) =>
        '<div class="risk risk-' + escapeHtml(r.severity) + '"><strong>[' + r.severity.toUpperCase() + '] ' +
        escapeHtml(r.title) + '</strong> — ' + escapeHtml(r.description) + '</div>'
      ).join('');
      wrap.innerHTML = '<h2>Review notes</h2>' + items;
      root.appendChild(wrap);
    }
  }

  if (doc.keyChanges && doc.keyChanges.length) {
    const wrap = document.createElement('section');
    const details = doc.keyChanges.map((c, i) => {
      const id = 'kc-' + i;
      const annotations = (c.annotations || []).map((a) =>
        '<li>' + (a.lineRange ? '<code>' + escapeHtml(a.lineRange) + '</code> — ' : '') + escapeHtml(a.note) + '</li>'
      ).join('');
      return '<details><summary>' + escapeHtml(c.path) + ' — ' + escapeHtml(c.summary) + '</summary>' +
        (c.rationale ? '<p>' + escapeHtml(c.rationale) + '</p>' : '') +
        (annotations ? '<ul>' + annotations + '</ul>' : '') +
        '</details>';
    }).join('');
    wrap.innerHTML = '<h2>Key changes</h2>' + details;
    root.appendChild(wrap);
  }

  if (doc.followUps && doc.followUps.length) {
    const wrap = document.createElement('section');
    wrap.innerHTML = '<h2>Follow-ups</h2><ul>' + doc.followUps.map((f) => '<li>' + escapeHtml(f) + '</li>').join('') + '</ul>';
    root.appendChild(wrap);
  }

  function badgeFor(status) {
    switch (status) {
      case 'added': return { cls: 'badge-A', label: 'A' };
      case 'modified': return { cls: 'badge-M', label: 'M' };
      case 'deleted': return { cls: 'badge-D', label: 'D' };
      case 'renamed': return { cls: 'badge-R', label: 'R' };
      case 'copied': return { cls: 'badge-C', label: 'C' };
      case 'touched': return { cls: 'badge-touched', label: '·' };
      case 'read': return { cls: 'badge-read', label: 'R' };
      default: return { cls: '', label: '?' };
    }
  }
  function escapeHtml(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  }
  function mdToHtml(md) {
    return escapeHtml(md).replace(/\n\n+/g, '<br/><br/>').replace(/\n/g, '<br/>');
  }
})();
</script>
</body>
</html>
`;
}

function escape(value: string): string {
	return value.replace(
		/[&<>"]/g,
		(c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] ?? c,
	);
}
